database:
 read:
   connstring: "postgres://postgres:postgres@localhost:5432/db_aob"
 write:
   connstring: "postgres://postgres:postgres@localhost:5432/db_aob"

 

kafka:
 consumer:
   topic: "test"
   broker:
     - localhost:9092

 

telemetry:
 enable: true
 service_name: "fetch"
 environment: dev
 jaeger:
   trace_ratio: 1
   agent_host: 127.0.0.1
   agent_port: 6831